### ISSUE TITLE
Problem running under Linux

### ISSUE THREAD

**Issue by Sadi58** [cmabad/ViHoMa#3]
Tried both openjdk-8-jre and the default openjdk-11-jre, but received the same terminal output:
**Error: Could not find or load main class application.Main**

**Comment by cmabad** [comment]
Hi, thanks for trying Vihoma. That error raises when the JavaFX packages are not found (they are not installed by default alongside the Java Runtime Environment).

If you are on Linux, it can be installed with your distro package manager (e.g, apt install openjfx).

For other operating systems, visit the [JavaFX webpage]( https://openjfx.io/), where the package can be easily downloaded and installed. That should fix the problem.

**Comment by Sadi58** [comment]
Thanks. Sorry for my oversight. However, I still can't make enough progress unfortunately. The terminal output now is:
```
Error: Could not find or load main class application.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application 
```
By the way, I attempted to improve the file "vihoma.sh" in this way for Kubuntu - perhaps it may further be improved by also including a zenity dialog box, etc.:

```
#!/usr/bin/env bash
# get sudo password
sudo_password=$( kdialog --title "Authentication Required" --password "<b><big>ViHoMa</big></b><br><br>An application is attempting to perform an action that requires admin privileges. Authentication is required to perform this action." -- : 2>/dev/null )
# check for null entry or cancellation
if [[ ${?} != 0 || -z ${sudo_password} ]]
then
	exit 4
fi
if ! sudo -kSp '' [ 1 ] <<<${sudo_password} 2>/dev/null
then
	exit 4
fi
# begin
# readlink follows any symbolic links to get the real file
REALVIHOMAPATH=`dirname "$(readlink -nf $0)"`
sudo -Sp '' java -jar "${REALVIHOMAPATH}/vihoma.jar" "$@" <<<${sudo_password}
```

**Comment by Unlocked8235** [comment]
I also had the same problem. Turns out OpenJDK doesn't include the JavaFX Library. OracleJDK however does.
I tried manually setting up JavaFX for OpenJDK, but failed. Installed OracleJDK, set it as default in my terminal and now ViHoMa works like a dream by executing vihoma.sh

**Comment by Sadi58** [comment]
@Unlocked8235 Thank you. I've tried doing the same in my system, which is _Debian Testing_, and installed _Oracle JDK 21_ from https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb but it still didn't work unfortunately.
The command `java -version` has this output:
```
java version "21.0.1" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.1+12-LTS-29, mixed mode, sharing)
```

And the command `sudo java -jar vihoma.jar` still gives this output:
```
Error: Could not find or load main class application.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```
